/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq;


import com.jooq.jooq.tables.Unrepresentative;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in jooq_tutorial.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UNREPRESENTATIVE_FK_COUNTRY_ID = Internal.createIndex(DSL.name("Fk_Country_Id"), Unrepresentative.UNREPRESENTATIVE, new OrderField[] { Unrepresentative.UNREPRESENTATIVE.FK_COUNTRY_ID }, false);
}
