/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq;


import com.jooq.jooq.tables.Country;
import com.jooq.jooq.tables.Unrepresentative;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTutorial extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_tutorial</code>
     */
    public static final JooqTutorial JOOQ_TUTORIAL = new JooqTutorial();

    /**
     * The table <code>jooq_tutorial.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>jooq_tutorial.unrepresentative</code>.
     */
    public final Unrepresentative UNREPRESENTATIVE = Unrepresentative.UNREPRESENTATIVE;

    /**
     * No further instances allowed
     */
    private JooqTutorial() {
        super("jooq_tutorial", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Country.COUNTRY,
            Unrepresentative.UNREPRESENTATIVE
        );
    }
}
