/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq;


import com.jooq.jooq.tables.Country;
import com.jooq.jooq.tables.Unrepresentative;
import com.jooq.jooq.tables.records.CountryRecord;
import com.jooq.jooq.tables.records.UnrepresentativeRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * jooq_tutorial.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CountryRecord> KEY_COUNTRY_PRIMARY = Internal.createUniqueKey(Country.COUNTRY, DSL.name("KEY_country_PRIMARY"), new TableField[] { Country.COUNTRY.PK_COUNTRY_ID }, true);
    public static final UniqueKey<UnrepresentativeRecord> KEY_UNREPRESENTATIVE_PRIMARY = Internal.createUniqueKey(Unrepresentative.UNREPRESENTATIVE, DSL.name("KEY_unrepresentative_PRIMARY"), new TableField[] { Unrepresentative.UNREPRESENTATIVE.PK_UNREPRESENTATIVE_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UnrepresentativeRecord, CountryRecord> UNREPRESENTATIVE_IBFK_1 = Internal.createForeignKey(Unrepresentative.UNREPRESENTATIVE, DSL.name("unrepresentative_ibfk_1"), new TableField[] { Unrepresentative.UNREPRESENTATIVE.FK_COUNTRY_ID }, Keys.KEY_COUNTRY_PRIMARY, new TableField[] { Country.COUNTRY.PK_COUNTRY_ID }, true);
}
