/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq;


import com.jooq.jooq.tables.Country;
import com.jooq.jooq.tables.Unrepresentative;


/**
 * Convenience access to all tables in jooq_tutorial.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_tutorial.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>jooq_tutorial.unrepresentative</code>.
     */
    public static final Unrepresentative UNREPRESENTATIVE = Unrepresentative.UNREPRESENTATIVE;
}
